package us.hebi.robobuf;

import us.hebi.robobuf.java.AllTypesOuterClass;
import us.hebi.robobuf.java.AllTypesOuterClass.ForeignEnum;
import us.hebi.robobuf.java.AllTypesOuterClass.TestAllSupportedTypes;
import us.hebi.robobuf.java.AllTypesOuterClass.TestAllSupportedTypes.NestedEnum;
import us.hebi.robobuf.java.external.ImportEnum;

/**
 * "ground-truth" data generated by protobuf-Java
 *
 * @author Florian Enner
 * @since 13 Aug 2019
 */
public class TestSamples {

    static byte[] optionalPrimitives() {
        TestAllSupportedTypes msg = TestAllSupportedTypes.newBuilder()
                .setId(99) // needs to be set
                .setOptionalBool(true)
                .setOptionalDouble(100.0d)
                .setOptionalFloat(101.0f)
                .setOptionalFixed32(102)
                .setOptionalFixed64(103)
                .setOptionalSfixed32(104)
                .setOptionalSfixed64(105)
                .setOptionalSint32(106)
                .setOptionalSint64(107)
                .setOptionalInt32(108)
                .setOptionalInt64(109)
                .setOptionalUint32(110)
                .setOptionalUint64(111)
                .build();
        return msg.toByteArray();
    }

    static byte[] optionalEnums() {
        TestAllSupportedTypes msg = TestAllSupportedTypes.newBuilder()
                .setId(0)
                .setOptionalNestedEnum(NestedEnum.FOO)
                .setOptionalForeignEnum(ForeignEnum.FOREIGN_BAR)
                .setOptionalImportEnum(ImportEnum.IMPORT_BAZ)
                .build();
        return msg.toByteArray();
    }

    static byte[] optionalString() {
        TestAllSupportedTypes msg = TestAllSupportedTypes.newBuilder()
                .setId(0)
                .setOptionalNestedEnum(NestedEnum.FOO)
                .setOptionalForeignEnum(ForeignEnum.FOREIGN_BAR)
                .setOptionalImportEnum(ImportEnum.IMPORT_BAZ)
                .build();
        return msg.toByteArray();
    }

}


