name: Native Plugin

on:
  push:
    branches: [ release/native-gen ]
  workflow_dispatch:
    inputs:

jobs:
  build-x86_64:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        components: 'native-image'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build x86_64 image
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        mvn package -Pnative --projects generator -am

    - name: Upload x86_64 build
      uses: actions/upload-artifact@v3
      with:
        name: native-images
        path: generator/target/*.exe
        retention-days: 10
        
  conveyor-site:
    needs: build-x86_64
    runs-on: [self-hosted, macos-aarch64]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    
    - name: Build aarch64 image
      run: |
        export JAVA_HOME=${GRAALVM_HOME}
        mvn clean package -Pnative --projects generator -am
      
    - name: Upload aarch64 build
      uses: actions/upload-artifact@v3
      with:
        name: native-images
        path: generator/target/*.exe
        retention-days: 10
    
    - name: Download native builds
      uses: actions/download-artifact@v3
      with:
        name: native-images
        path: generator/native-release/bin/
        
    - name: Conveyor site
      working-directory: ./generator/native-release
      run: |
        chmod +x bin/*.exe
        conveyor make site
      
    - name: Upload site
      uses: actions/upload-artifact@v3
      with:
        name: conveyor-site
        path: generator/native-release/output/*
        retention-days: 10
      
    
