name: Native Plugin

on:
  push:
    branches: [ release/native-gen ]
  workflow_dispatch:
    inputs:

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11, macos-aarch64]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        components: 'native-image'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build native image
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        mvn package -Pnative --projects generator -am

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: protoc-gen-quickbuf
        path: generator/target/*.exe
