name: Native Plugin

on:
  push:
    branches: [ release/native-gen ]
  workflow_dispatch:
    inputs:

jobs:
  build-images:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-11, [self-hosted, linux-aarch64], [self-hosted, macos-aarch64]]

    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.1
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '21'
        set-java-home: 'true'
        components: 'native-image'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build native image
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        mvn clean package -Pnative --projects generator -am

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: native-images
        path: generator/target/*.exe
        retention-days: 10

  conveyor-site:
    needs: [build-images]
    runs-on: [self-hosted, macos-aarch64]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.1

    - name: Download native builds
      uses: actions/download-artifact@v3
      with:
        name: native-images
        path: generator/native-release/bin/
        
    - name: Conveyor site
      working-directory: ./generator/native-release
      run: |
        mvn clean package
        conveyor make site
      
    - name: Upload site
      uses: actions/upload-artifact@v3
      with:
        name: conveyor-site
        path: generator/native-release/output/*
        retention-days: 10
      
